[package]
name = "joycon2click"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "*"
uinput = "*"
# locked, because of this not being merged https://github.com/meh/rust-uinput/pull/16
# newer version fail to build due to https://github.com/nix-rust/nix/pull/1446
nix = "0.10.0"
