[package]
name = "joycon2click"
version = "0.1.0"
edition = "2021"
authors= ["Michaël Scherer"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "*"
# see https://github.com/meh/rust-uinput/pull/16
uinput = { version = "*", git = "https://github.com/JBBgameich/rust-uinput", branch = "update-nix" }

# locked, because of this not being merged https://github.com/meh/rust-uinput/pull/16
# newer version fail to build due to https://github.com/nix-rust/nix/pull/1446
nix = "0.23.0"
netlink-sys = "*"
kobject-uevent = "*"
clap = { version = "*", features = ["derive"] }
