on: [push, pull_request]

name: Compile and lint

jobs:
  check:
    strategy:
      matrix:
        rust_version: [stable, nightly]

    name: Build rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ${{ matrix.rust_version }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: ${{ matrix.rust_version }}
            override: true
            components: rustfmt, clippy

      # TODO refactor ?
      - name: Run cargo build
        uses: clechasseur/rs-cargo@v2
        with:
          command: build
          args: --release

      - name: Run cargo fmt
        uses: clechasseur/rs-cargo@v2
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: clechasseur/rs-cargo@v2
        with:
          command: clippy
          args: -- -D warnings

